<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\PetPresence.Contracts\PetPresence.Contracts.csproj" />
    <ProjectReference Include="..\..\src\PetPresence.Desktop\PetPresence.Desktop.csproj" />
    <ProjectReference Include="..\..\src\PetPresence.Server\PetPresence.Server.csproj" />
  </ItemGroup>
</Project>
